config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  mount ActionCable.server => '/cable'

  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper

  get '.well-known/host-meta', to: 'xrd#host_meta', as: :host_meta
  get '.well-known/webfinger', to: 'xrd#webfinger', as: :webfinger

  devise_for :users, path: 'auth', controllers: {
    sessions:           'auth/sessions',
    registrations:      'auth/registrations',
    passwords:          'auth/passwords',
    confirmations:      'auth/confirmations'
  }

  resources :accounts, path: 'users', only: [:show], param: :username do
    resources :stream_entries, path: 'updates', only: [:show]

    member do
      get :followers
      get :following

      post :follow
      post :unfollow
    end
  end

  resource  :settings, only: [:show, :update]
  resources :media, only: [:show]

  namespace :api do
    # PubSubHubbub
    resources :subscriptions, only: [:show]
    post '/subscriptions/:id', to: 'subscriptions#update'

    # Salmon
    post '/salmon/:id', to: 'salmon#update', as: :salmon

    # JSON / REST API
    namespace :v1 do
      resources :statuses, only: [:create, :show, :destroy] do
        collection do
          get :home
          get :mentions
          get :public
        end

        member do
          get :context

          post :reblog
          post :unreblog
          post :favourite
          post :unfavourite
        end
      end

      resources :follows,  only: [:create]
      resources :media,    only: [:create]
      resources :apps,     only: [:create]

      resources :accounts, only: [:show] do
        collection do
          get :relationships
          get :verify_credentials
        end

        member do
          get :statuses
          get :followers
          get :following

          post :follow
          post :unfollow
          post :block
          post :unblock
        end
      end
    end
  end

  get :about, to: 'about#index'

  root 'home#index'

  match '*unmatched_route', via: :all, to: 'application#raise_not_found'
end

app/models/stream_entry.rb
class StreamEntry < ApplicationRecord
  include Paginable

  belongs_to :account, inverse_of: :stream_entries
  belongs_to :activity, polymorphic: true

  belongs_to :status,    foreign_type: 'Status',    foreign_key: 'activity_id'
  belongs_to :follow,    foreign_type: 'Follow',    foreign_key: 'activity_id'
  belongs_to :favourite, foreign_type: 'Favourite', foreign_key: 'activity_id'

  validates :account, :activity, presence: true

  STATUS_INCLUDES = [:account, :stream_entry, :media_attachments, mentions: :account, reblog: [:stream_entry, :account, mentions: :account], thread: [:stream_entry, :account]].freeze

  scope :with_includes, -> { includes(:account, status: STATUS_INCLUDES, favourite: [:account, :stream_entry, status: STATUS_INCLUDES], follow: [:target_account, :stream_entry]) }

  def object_type
    orphaned? ? :activity : (targeted? ? :activity : activity.object_type)
  end

  def verb
    orphaned? ? :delete : activity.verb
  end

  def targeted?
    [:follow, :share, :favorite].include? verb
  end

  def target
    orphaned? ? nil : activity.target
  end

  def title
    orphaned? ? nil : activity.title
  end

  def content
    orphaned? ? nil : activity.content
  end

  def threaded?
    (verb == :favorite || object_type == :comment) && !thread.nil?
  end

  def thread
    orphaned? ? nil : activity.thread
  end

  def mentions
    activity.respond_to?(:mentions) ? activity.mentions.map(&:account) : []
  end

  def activity
    send(activity_type.downcase.to_sym)
  end

  private

  def orphaned?
    activity.nil?
  end
end

app/controllers/stream_entries_controller.rb
class StreamEntriesController < ApplicationController
  layout 'public'

  before_action :set_account
  before_action :set_stream_entry
  before_action :set_link_headers

  def show
    @type = @stream_entry.activity_type.downcase

    respond_to do |format|
      format.html do
        return gone if @stream_entry.activity.nil?

        if @stream_entry.activity_type == 'Status'
          @ancestors   = @stream_entry.activity.ancestors
          @descendants = @stream_entry.activity.descendants
        end
      end

      format.atom
    end
  end

  private

  def set_account
    @account = Account.find_local!(params[:account_username])
  end

  def set_link_headers
    response.headers['Link'] = LinkHeader.new([
      [account_stream_entry_url(@account, @stream_entry, format: 'atom'), [['rel', 'alternate'], ['type', 'application/atom+xml']]]
    ])
  end

  def set_stream_entry
    @stream_entry = @account.stream_entries.find(params[:id])
  end
end

app/helpers/stream_entries_helper.rb
module StreamEntriesHelper
  def display_name(account)
    account.display_name.blank? ? account.username : account.display_name
  end

  def avatar_for_status_url(status)
    status.reblog? ? status.reblog.account.avatar.url(:medium) : status.account.avatar.url(:medium)
  end

  def entry_classes(status, is_predecessor, is_successor, include_threads)
    classes = ['entry']
    classes << 'entry-reblog' if status.reblog?
    classes << 'entry-predecessor' if is_predecessor
    classes << 'entry-successor' if is_successor
    classes << 'entry-center' if include_threads
    classes.join(' ')
  end

  def relative_time(date)
    date < 5.days.ago ? date.strftime('%d.%m.%Y') : "#{time_ago_in_words(date)} ago"
  end

  def reblogged_by_me_class(status)
    user_signed_in? && @reblogged.key?(status.id) ? 'reblogged' : ''
  end

  def favourited_by_me_class(status)
    user_signed_in? && @favourited.key?(status.id) ? 'favourited' : ''
  end

  def proper_status(status)
    status.reblog? ? status.reblog : status
  end
end

app/views/stream_entries/_favourite.html.haml
.entry.entry-favourite
  .content
    %strong= favourite.account.acct
    favourited a post by
    %strong= favourite.status.account.acct

app/views/stream_entries/_follow.html.haml
.entry.entry-follow
  .content
    %strong= link_to follow.account.acct, account_path(follow.account)
    is now following
    %strong= link_to follow.target_account.acct, TagManager.instance.url_for(follow.target_account)

app/views/stream_entries/_status.html.haml
- include_threads ||= false
- is_predecessor  ||= false
- is_successor    ||= false
- centered          = include_threads && !is_predecessor && !is_successor

- if status.reply? && include_threads
  = render partial: 'status', collection: @ancestors, as: :status, locals: { is_predecessor: true }

.entry{ class: entry_classes(status, is_predecessor, is_successor, include_threads) }
  - if status.reblog?
    .pre-header
      %i.fa.fa-retweet
      Shared by
      = link_to display_name(status.account), TagManager.instance.url_for(status.account), class: 'name'

  .entry__container
    .avatar
      = image_tag avatar_for_status_url(status)

    .entry__container__container
      .header
        .header__left
          = link_to TagManager.instance.url_for(proper_status(status).account), class: 'name' do
            %strong= display_name(proper_status(status).account)
            = "@#{proper_status(status).account.acct}"

        .header__right
          = link_to TagManager.instance.url_for(proper_status(status)), class: 'time' do
            %span{ title: proper_status(status).created_at }
              = relative_time(proper_status(status).created_at)

      .content= Formatter.instance.format(proper_status(status))

      %ul.media-attachments
        - (status.reblog? ? status.reblog : status).media_attachments.each do |media|
          %li.transparent-background= link_to '', media.file.url, style: "background-image: url(#{media.file.url(:small)})", target: '_blank'

- if include_threads
  = render partial: 'status', collection: @descendants, as: :status, locals: { is_successor: true }

app/views/stream_entries/show.html.haml
- content_for :header_tags do
  %link{ rel: 'alternate', type: 'application/atom+xml', href: account_stream_entry_url(@account, @stream_entry, format: 'atom') }/

.activity-stream.activity-stream-headless
  = render partial: @type, locals: { @type.to_sym => @stream_entry.activity, include_threads: true }