config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  mount ActionCable.server => '/cable'

  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper

  get '.well-known/host-meta', to: 'xrd#host_meta', as: :host_meta
  get '.well-known/webfinger', to: 'xrd#webfinger', as: :webfinger

  devise_for :users, path: 'auth', controllers: {
    sessions:           'auth/sessions',
    registrations:      'auth/registrations',
    passwords:          'auth/passwords',
    confirmations:      'auth/confirmations'
  }

  resources :accounts, path: 'users', only: [:show], param: :username do
    resources :stream_entries, path: 'updates', only: [:show]

    member do
      get :followers
      get :following

      post :follow
      post :unfollow
    end
  end

  resource  :settings, only: [:show, :update]
  resources :media, only: [:show]

  namespace :api do
    # PubSubHubbub
    resources :subscriptions, only: [:show]
    post '/subscriptions/:id', to: 'subscriptions#update'

    # Salmon
    post '/salmon/:id', to: 'salmon#update', as: :salmon

    # JSON / REST API
    namespace :v1 do
      resources :statuses, only: [:create, :show, :destroy] do
        collection do
          get :home
          get :mentions
          get :public
        end

        member do
          get :context

          post :reblog
          post :unreblog
          post :favourite
          post :unfavourite
        end
      end

      resources :follows,  only: [:create]
      resources :media,    only: [:create]
      resources :apps,     only: [:create]

      resources :accounts, only: [:show] do
        collection do
          get :relationships
          get :verify_credentials
        end

        member do
          get :statuses
          get :followers
          get :following

          post :follow
          post :unfollow
          post :block
          post :unblock
        end
      end
    end
  end

  get :about, to: 'about#index'

  root 'home#index'

  match '*unmatched_route', via: :all, to: 'application#raise_not_found'
end

app/models/account.rb
class Account < ApplicationRecord
  include Targetable

  MENTION_RE = /(?:^|\s|\.|>)@([a-z0-9_]+(?:@[a-z0-9\.\-]+)?)/i
  IMAGE_MIME_TYPES = ['image/jpeg', 'image/png', 'image/gif'].freeze

  # Local users
  has_one :user, inverse_of: :account
  validates :username, presence: true, format: { with: /\A[a-z0-9_]+\z/i, message: 'only letters, numbers and underscores' }, uniqueness: { scope: :domain, case_sensitive: false }, length: { maximum: 30 }, if: 'local?'
  validates :username, presence: true, uniqueness: { scope: :domain, case_sensitive: true }, unless: 'local?'

  # Avatar upload
  has_attached_file :avatar, styles: { large: '300x300#', medium: '96x96#', small: '48x48#' }
  validates_attachment_content_type :avatar, content_type: IMAGE_MIME_TYPES
  validates_attachment_size :avatar, less_than: 2.megabytes

  # Header upload
  has_attached_file :header, styles: { medium: '700x335#' }
  validates_attachment_content_type :header, content_type: IMAGE_MIME_TYPES
  validates_attachment_size :header, less_than: 2.megabytes

  # Local user profile validations
  validates :display_name, length: { maximum: 30 }, if: 'local?'
  validates :note, length: { maximum: 124 }, if: 'local?'

  # Timelines
  has_many :stream_entries, inverse_of: :account, dependent: :destroy
  has_many :statuses, inverse_of: :account, dependent: :destroy
  has_many :favourites, inverse_of: :account, dependent: :destroy
  has_many :mentions, inverse_of: :account, dependent: :destroy

  # Follow relations
  has_many :active_relationships,  class_name: 'Follow', foreign_key: 'account_id',        dependent: :destroy
  has_many :passive_relationships, class_name: 'Follow', foreign_key: 'target_account_id', dependent: :destroy

  has_many :following, -> { order('follows.created_at desc') }, through: :active_relationships,  source: :target_account
  has_many :followers, -> { order('follows.created_at desc') }, through: :passive_relationships, source: :account

  # Block relationships
  has_many :block_relationships, class_name: 'Block', foreign_key: 'account_id', dependent: :destroy
  has_many :blocking, -> { order('blocks.created_at desc') }, through: :block_relationships, source: :target_account

  has_many :media_attachments, dependent: :destroy

  scope :remote, -> { where.not(domain: nil) }
  scope :local, -> { where(domain: nil) }
  scope :without_followers, -> { where('(select count(f.id) from follows as f where f.target_account_id = accounts.id) = 0') }
  scope :with_followers, -> { where('(select count(f.id) from follows as f where f.target_account_id = accounts.id) > 0') }
  scope :expiring, -> (time) { where(subscription_expires_at: nil).or(where('subscription_expires_at < ?', time)).remote.with_followers }

  def follow!(other_account)
    active_relationships.where(target_account: other_account).first_or_create!(target_account: other_account)
  end

  def block!(other_account)
    block_relationships.where(target_account: other_account).first_or_create!(target_account: other_account)
  end

  def unfollow!(other_account)
    follow = active_relationships.find_by(target_account: other_account)
    follow.destroy unless follow.nil?
  end

  def unblock!(other_account)
    block = block_relationships.find_by(target_account: other_account)
    block.destroy unless block.nil?
  end

  def following?(other_account)
    following.include?(other_account)
  end

  def blocking?(other_account)
    blocking.include?(other_account)
  end

  def local?
    domain.nil?
  end

  def acct
    local? ? username : "#{username}@#{domain}"
  end

  def subscribed?
    !subscription_expires_at.nil?
  end

  def favourited?(status)
    (status.reblog? ? status.reblog : status).favourites.where(account: self).count > 0
  end

  def reblogged?(status)
    (status.reblog? ? status.reblog : status).reblogs.where(account: self).count > 0
  end

  def keypair
    private_key.nil? ? OpenSSL::PKey::RSA.new(public_key) : OpenSSL::PKey::RSA.new(private_key)
  end

  def subscription(webhook_url)
    OStatus2::Subscription.new(remote_url, secret: secret, lease_seconds: 86_400 * 30, webhook: webhook_url, hub: hub_url)
  end

  def ping!(atom_url, hubs)
    return unless local? && !Rails.env.development?
    OStatus2::Publication.new(atom_url, hubs).publish
  end

  def avatar_remote_url=(url)
    self.avatar = URI.parse(url) unless self[:avatar_remote_url] == url
    self[:avatar_remote_url] = url
  end

  def object_type
    :person
  end

  def to_param
    username
  end

  def self.find_local!(username)
    find_remote!(username, nil)
  end

  def self.find_remote!(username, domain)
    where(arel_table[:username].matches(username)).where(domain.nil? ? { domain: nil } : arel_table[:domain].matches(domain)).take!
  end

  def self.find_local(username)
    find_local!(username)
  rescue ActiveRecord::RecordNotFound
    nil
  end

  def self.find_remote(username, domain)
    find_remote!(username, domain)
  rescue ActiveRecord::RecordNotFound
    nil
  end

  def self.following_map(target_account_ids, account_id)
    Follow.where(target_account_id: target_account_ids).where(account_id: account_id).map { |f| [f.target_account_id, true] }.to_h
  end

  def self.followed_by_map(target_account_ids, account_id)
    Follow.where(account_id: target_account_ids).where(target_account_id: account_id).map { |f| [f.account_id, true] }.to_h
  end

  def self.blocking_map(target_account_ids, account_id)
    Block.where(target_account_id: target_account_ids).where(account_id: account_id).map { |b| [b.target_account_id, true] }.to_h
  end

  before_create do
    if local?
      keypair = OpenSSL::PKey::RSA.new(Rails.env.test? ? 1024 : 2048)
      self.private_key = keypair.to_pem
      self.public_key  = keypair.public_key.to_pem
    end
  end
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  layout 'public'

  before_action :set_account
  before_action :set_link_headers

  def show
    respond_to do |format|
      format.html do
        @statuses = @account.statuses.order('id desc').with_includes.with_counters.paginate(page: params[:page], per_page: 10)
      end

      format.atom do
        @entries = @account.stream_entries.order('id desc').with_includes.paginate_by_max_id(20, params[:max_id] || nil)
      end
    end
  end

  def follow
    FollowService.new.call(current_user.account, @account.acct)
    redirect_to account_path(@account)
  end

  def unfollow
    UnfollowService.new.call(current_user.account, @account)
    redirect_to account_path(@account)
  end

  def followers
    @followers = @account.followers.order('follows.created_at desc').paginate(page: params[:page], per_page: 6)
  end

  def following
    @following = @account.following.order('follows.created_at desc').paginate(page: params[:page], per_page: 6)
  end

  private

  def set_account
    @account = Account.find_local!(params[:username])
  end

  def set_link_headers
    response.headers['Link'] = LinkHeader.new([
      [webfinger_account_url, [['rel', 'lrdd'], ['type', 'application/xrd+xml']]],
      [account_url(@account, format: 'atom'), [['rel', 'alternate'], ['type', 'application/atom+xml']]]
    ])
  end

  def webfinger_account_url
    webfinger_url(resource: "acct:#{@account.acct}@#{Rails.configuration.x.local_domain}")
  end
end

app/controllers/api/v1/accounts_controller.rb
class Api::V1::AccountsController < ApiController
  before_action :doorkeeper_authorize!
  before_action :set_account, except: :verify_credentials
  respond_to    :json

  def show
  end

  def verify_credentials
    @account = current_user.account
    render action: :show
  end

  def following
    @following = @account.following
  end

  def followers
    @followers = @account.followers
  end

  def statuses
    @statuses = @account.statuses.with_includes.with_counters.paginate_by_max_id(20, params[:max_id], params[:since_id]).to_a
  end

  def follow
    FollowService.new.call(current_user.account, @account.acct)
    set_relationship
    render action: :relationship
  end

  def block
    BlockService.new.call(current_user.account, @account)
    set_relationship
    render action: :relationship
  end

  def unfollow
    UnfollowService.new.call(current_user.account, @account)
    set_relationship
    render action: :relationship
  end

  def unblock
    UnblockService.new.call(current_user.account, @account)
    set_relationship
    render action: :relationship
  end

  def relationships
    ids = params[:id].is_a?(Enumerable) ? params[:id].map(&:to_i) : [params[:id].to_i]
    @accounts    = Account.find(ids)
    @following   = Account.following_map(ids, current_user.account_id)
    @followed_by = Account.followed_by_map(ids, current_user.account_id)
    @blocking    = Account.blocking_map(ids, current_user.account_id)
  end

  private

  def set_account
    @account = Account.find(params[:id])
  end

  def set_relationship
    @following   = Account.following_map([@account.id], current_user.account_id)
    @followed_by = Account.followed_by_map([@account.id], current_user.account_id)
    @blocking    = Account.blocking_map([@account.id], current_user.account_id)
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
  def pagination_options
    {
      previous_label: "#{fa_icon('chevron-left')} Prev".html_safe,
      next_label: "Next #{fa_icon('chevron-right')}".html_safe,
      inner_window: 1,
      outer_window: 0
    }
  end
end

app/views/accounts/_grid_card.html.haml
.account-grid-card
  .account-grid-card__header
    .avatar= image_tag account.avatar.url(:medium)
    .name
      = link_to TagManager.instance.url_for(account) do
        %span.display_name= display_name(account)
        %span.username= "@#{account.acct}"
  %p.note= truncate(strip_tags(account.note), length: 150)

app/views/accounts/_header.html.haml
.card{ style: "background-image: url(#{@account.header.url(:medium)})" }
  - if user_signed_in? && current_account.id != @account.id
    .controls
      - if current_account.following?(@account)
        = link_to 'Unfollow', unfollow_account_path(@account), data: { method: :post }, class: 'button'
      - else
        = link_to 'Follow', follow_account_path(@account), data: { method: :post }, class: 'button'

  .avatar= image_tag @account.avatar.url(:large)
  %h1.name
    = display_name(@account)
    %small= "@#{@account.username}"
  .details
    .bio
      %p= @account.note

    .details-counters
      .counter{ class: active_nav_class(account_url(@account)) }
        = link_to account_url(@account) do
          %span.counter-label Posts
          %span.counter-number= @account.statuses.count
      .counter{ class: active_nav_class(following_account_url(@account)) }
        = link_to following_account_url(@account) do
          %span.counter-label Following
          %span.counter-number= @account.following.count
      .counter{ class: active_nav_class(followers_account_url(@account)) }
        = link_to followers_account_url(@account) do
          %span.counter-label Followers
          %span.counter-number= @account.followers.count

app/views/accounts/_nothing_here.html.haml
%p.nothing-here There is nothing here!

app/views/accounts/followers.html.haml
- content_for :page_title do
  People who follow
  = display_name(@account)

= render partial: 'header'

.accounts-grid
  - if @followers.empty?
    = render partial: 'nothing_here'
  - else
    = render partial: 'grid_card', collection: @followers, as: :account

= will_paginate @followers, pagination_options

app/views/accounts/following.html.haml
- content_for :page_title do
  People whom
  = display_name(@account)
  follows

= render partial: 'header'

.accounts-grid
  - if @following.empty?
    = render partial: 'nothing_here'
  - else
    = render partial: 'grid_card', collection: @following, as: :account

= will_paginate @following, pagination_options

app/views/accounts/show.html.haml
- content_for :page_title do
  = display_name(@account)

- content_for :header_tags do
  %link{ rel: 'salmon', href: api_salmon_url(@account.id) }/
  %link{ rel: 'alternate', type: 'application/atom+xml', href: account_url(@account, format: 'atom') }/

= render partial: 'header'

- if @statuses.empty?
  .accounts-grid
    = render partial: 'nothing_here'
- else
  .activity-stream
    = render partial: 'stream_entries/status', collection: @statuses, as: :status

= will_paginate @statuses, pagination_options